### PR TITLE
Fixes testing errors

### PR DESCRIPTION
**Pull request by JJ**
While trying to add this to ecosystem. https://travis-ci.org/perl6/ecosystem/builds/497837363?utm_source=github_status&utm_medium=notification

### CODE REVIEW

**Review by alabamenhu — APPROVED** [review]

**Comment by alabamenhu** [comment]
Thanks for the fixes!

**Comment by JJ** [comment]
I have added it finally to the ecosystem, too. It's going to be released
this noon, probably.

**Comment by alabamenhu** [comment]
Great.  Thanks again.  I'll be more careful in the future with the JSON data

**Comment by JJ** [comment]
No problem. Testing took so long that people simply forgot. That's been
fixed now :-)

**Pull request merged**
